version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: MemoryBox
    volumes:
      - .:/MemoryBox
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    expose:
      - 3306
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: 'MemoryBox-mysql'
      MYSQL_PORT: '3306'
      MYSQL_ROOT_PASSWORD: ********
    volumes:
      - ./data/mysql/db:/var/lib/mysql