# Generated by Django 4.1.3 on 2022-11-28 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saving',
            field=models.ManyToManyField(blank=True, related_name='saving', to=settings.AUTH_USER_MODEL),
        ),
    ]
